"""add language to posts

Revision ID: 939e9cd9bbb1
Revises: d575f324c99c
Create Date: 2021-04-30 19:10:14.308195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939e9cd9bbb1'
down_revision = 'd575f324c99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
